language: scala
scala:
  - 2.11.8
  - 2.12.4
jdk:
  - oraclejdk8
  - oraclejdk7
matrix:
  exclude: # NB: Scala 2.12 requires JDK 8
  - scala: 2.12.4
    jdk: oraclejdk7

sudo: false
script:
  - sbt coverage tests/run tut coverageReport
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
after_success:
  - bash <(curl -s https://codecov.io/bash)
